name: appai

packages:
  - app
  - packages/**

scripts:

  analyze:
    exec: dart analyze .

  generate:
    run: dart run build_runner build --delete-conflicting-outputs
    exec:
      concurrency: 1
      orderDependents: true
    packageFilters:
      dependsOn: build_runner
